[package]
name="lib_video_objs"
version="0.0.1"
edition = "2021"

[lib]
name="lib_video_objs"
crate-type=["lib"]

[dependencies]
env_logger = "0.10.0"
dotenv = "0.15.0"
envy = "0.4.2"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
log = "0.4.17"
base64 = "0.21.2"
async-trait = "0.1.68"
url = {version="2.3.1", features=["serde"] }
uuid = { version = "1.3.3", features = ["v4","fast-rng",  "macro-diagnostics",  "serde"]}
