[package]
name="lib_async_ops"
version="0.0.1"
edition = "2021"

[lib]
name="lib_async_ops"
crate-type=["lib"]


[dependencies]
lib_config = { path = "../lib_config" }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.102"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["fmt", "env-filter"] }
validator = { version = "0.16", features = ["derive"] }
url = {version="2.4.0", features=["serde"] }
uuid = { version = "1.4.0", features = ["v4","fast-rng",  "macro-diagnostics",  "serde"]}
aws-sdk-sqs = "0.28.0"
aws-sdk-sns = "0.28.0"
env_logger = "0.10.0"

[dev-dependencies]
tokio = { version="1.29.1", features=["full"]}
spectral = "0.6.0"
testcontainers = { git="https://github.com/joanmiespada/testcontainers-rs", branch="localstack2"  }
