[package]
name="lib_config"
version="0.0.9"
edition = "2021"

[lib]
name="lib_config"
crate-type=["lib"]

[[test]]
name="integration"
path="tests/lib.rs"

[dependencies]
aws-sdk-dynamodb = "0.28.0"
aws-config = "0.55.3"
env_logger = "0.10.0"
dotenv = "0.15.0"
envy = "0.4.2"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
aws-sdk-secretsmanager = "0.28.0"
log = "0.4.17"
aws-types = "0.55.3"
aws-sdk-kms = "0.28.0"
base64 = "0.21.2"
async-trait = "0.1.68"
opentelemetry = { version = "0.19.0", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-otlp = "0.12.0"
opentelemetry-semantic-conventions = "0.11.0"
tracing-bunyan-formatter = "0.3.7"
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = {version="2.4.0", features = ["serde"]}

[dev-dependencies]
env_logger = "0.10.0"
aws-types = "0.55.3"
spectral = "0.6.0"
#testcontainers = "0.14.0"
testcontainers = { git="https://github.com/joanmiespada/testcontainers-rs", branch="localstack2"  }
tokio = { version="1.28.1", features=["full"]}
